# Remote test FDP
catalog_url: http://178.63.49.197:8051/catalog/d02af5a9-038f-44da-9447-0370fde9d9b4

# Local test FDP
# catalog_url: http://localhost/catalog/72d363a3-7995-4358-a95c-b56083d2243d

# FDP template
dataset_file: "test-input/datasets.csv"
distribution: "test-input/distributions.csv"

# EJPRD template
# ejp_vp_file: vp_test_input/EJPRD_Resource_Metadata_template.xlsx

# Dry run?
dry_run: false